name: CI/CD FastAPI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "export PATH=\"$HOME/.local/bin:$PATH\"" >> $GITHUB_ENV

      - name: Instalar dependências
        run: |
          poetry install --no-interaction --no-root

      - name: Executar testes
        run: |
          PYTHONPATH=$(pwd) poetry run pytest tests --log-cli-level=INFO
  
  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy no Render
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
